configured_endpoints: 47
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Funusualwhales-5e2753adcf80181401b67f2fa183d2eeb8a301b94aa1ad1c5ef861982a579d0f.yml
